name: Zip and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          zip -r ukrainian-mods-translate.zip all/

      - name: Read CHANGELOG
        id: changelog
        run: |
          echo "body=$(cat CHANGELOG.md)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: ${{ steps.changelog.outputs.body }}
          files: ukrainian-mods-translate.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
